
title: Kevin Raymond Profile
url: 'http://linkedin.com.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Kevin Raymond  ## put your name
title: ' &amp; IT'  ## your title
location: Miami , FL


## Social Profiles
linkedin: https://www.linkedin.com/in/kevin-raymond-15975442/  ## your linkedin account url




# Update all the sections by editing the files inside _includes folder.
